/PhysicsList/OmitMuonicProcesses true
/PhysicsList/OmitHadronicProcesses true 

/PhysicsList/SelectCerenkovProcess SNOMAN

/rat/db/set DETECTOR geo_file "geo/snoman_salt.geo

/run/initialize

# BEGIN EVENT LOOP
/rat/proc frontend
/rat/proc trigger
/rat/proc eventbuilder
/rat/proc calibratePMT

/rat/proc count
/rat/procset update 100

/rat/proc outroot
/rat/procset file "test.root"

# END EVENT LOOP
/generator/add combo gun:point:poisson
/generator/vtx/set gamma 0 0 0 2.0
/generator/pos/set 0 0 0
/generator/rate/set 1

/rat/run/start 1000
exit
